brasileirao <- read.csv("/home/igazev/Documentos/2020.2/Databases/dataset-2003-2020.csv", sep = ";")
attach(brasileirao)
View(brasileirao)
summary(brasileirao)
summary(points)
sd(points)
boxplot(points, notch = TRUE, outline = FALSE, ylab = ("Pontuações finais das equipes"))
help("boxplot")
hist(points, ylab = ("Frequência"), xlab = ("Pontuação final de cada equipe"), main = ("Histograma da pontuação das equipes"))
plot(year, points)
